---
# IUS yum repository.
- name: Set distribution major version
  set_fact:
    _distribution_major_version: "{{ ansible_distribution_version.split('.')[0] }}"
  tags: ['set_fact']

- name: Install EPEL.
  package:
    name: epel-release
    state: present
  tags: ['package']

- name: Instal Remi repository key
  rpm_key:
      state: present
      key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
  when: php_install_version == 8.1

- name: Instal Remi repository
  package:
    name: https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
    state: present
  tags: ['package']
  when: php_install_version == 8.1

- name: Install a modularity appstream with remi-8.1
  dnf:
    name: '@php:remi-{{ php_install_version }}'
    state: present
  when: php_install_version == 8.1

- name: Instal IUS
  package:
    name: https://repo.ius.io/ius-release-el{{ ansible_distribution_major_version }}.rpm
    state: present
  tags: ['package']
  when: php_install_version != 8.1

- name: Instal IUS
  package:
    name: https://repo.ius.io/ius-release-el{{ ansible_distribution_major_version }}.rpm
    state: present
  tags: ['package']
  when: php_install_version != 8.1
